"""
============================================================================
FILE: services/ingest/app/metadata_extractor.py
PURPOSE: Extract metadata from Markdown documents for attaching to Qdrant
         vector payloads and PostgreSQL document records.
ARCHITECTURE REF: §3.1 — Ingestion Pipeline (metadata preservation)
DEPENDENCIES: re (stdlib)
============================================================================
"""

import re
from typing import Any


def extract_frontmatter(markdown_text: str) -> dict[str, str]:
    """
    Parse the YAML frontmatter block at the top of a Markdown document.

    Frontmatter is generated by markdown_converter.py and looks like:
        ---
        filename: HR_Policy_2024.pdf
        format: pdf
        upload_date: 2026-02-20
        page_count: 15
        ---

    Args:
        markdown_text: Full markdown document.

    Returns:
        Dict of frontmatter key-value pairs (all values as strings).
        Empty dict if no frontmatter found.
    """
    # Match the frontmatter block between --- delimiters at the start
    match = re.match(r"^---\n(.*?)\n---", markdown_text, re.DOTALL)
    if not match:
        return {}

    frontmatter: dict[str, str] = {}
    for line in match.group(1).split("\n"):
        if ":" in line:
            key, _, value = line.partition(":")
            frontmatter[key.strip()] = value.strip()

    return frontmatter


def extract_section_headings(markdown_text: str) -> list[str]:
    """
    Extract all section headings from a Markdown document.

    Used to populate the document-level metadata record in PostgreSQL,
    enabling admin search and citation quality review.

    Args:
        markdown_text: Full markdown document.

    Returns:
        List of heading texts (without # symbols) in document order.
    """
    headings = []
    for line in markdown_text.split("\n"):
        match = re.match(r"^(#{1,6})\s+(.*)", line)
        if match:
            headings.append(match.group(2).strip())
    return headings


def build_document_metadata(
    markdown_text: str,
    filename: str,
    file_size_bytes: int,
    chunk_count: int = 0,
) -> dict[str, Any]:
    """
    Build the complete metadata dict to store in the PostgreSQL documents.metadata JSONB field.

    This metadata is stored alongside the document record and also indexed
    by Qdrant for payload filtering (e.g., "find chunks from this specific document").

    Args:
        markdown_text: The converted markdown content.
        filename: Original filename.
        file_size_bytes: File size for storage tracking.
        chunk_count: Number of chunks generated (0 until processing completes).

    Returns:
        Dict suitable for JSONB storage in PostgreSQL.
    """
    frontmatter = extract_frontmatter(markdown_text)
    headings = extract_section_headings(markdown_text)

    return {
        "filename": filename,
        "format": frontmatter.get("format", "unknown"),
        "upload_date": frontmatter.get("upload_date", ""),
        "page_count": int(frontmatter.get("page_count", 0) or 0),
        "chunk_count": chunk_count,
        "file_size_bytes": file_size_bytes,
        "section_headings": headings[:50],  # Cap at 50 headings for JSONB size
        "heading_count": len(headings),
    }


def build_chunk_payload(
    chunk,
    document_id: str,
    filename: str,
) -> dict[str, Any]:
    """
    Build the Qdrant vector payload for a single chunk.

    This payload is stored alongside the vector in Qdrant and returned
    in search results. It enables rich source citations in LLM responses.

    Args:
        chunk: DocumentChunk object from chunker.py.
        document_id: UUID of the parent document in PostgreSQL.
        filename: Original filename.

    Returns:
        Dict to use as Qdrant point payload.
        Keys must match the indexes created in qdrant_client_wrapper.py.
    """
    return {
        # These three are indexed in Qdrant for fast payload filtering
        "document_id": document_id,   # KEYWORD index — filter by document
        "filename": filename,         # KEYWORD index — show in citations
        "section": chunk.section_heading,  # TEXT index — search within sections

        # Additional metadata for citation quality
        "page_number": chunk.page_number,
        "chunk_index": chunk.chunk_index,
        "heading_path": " > ".join(chunk.heading_path) if chunk.heading_path else "",
        "token_count": chunk.token_count,

        # The actual chunk text — returned by Qdrant so we don't need a separate DB lookup
        "text": chunk.text,
    }
